## Topic: Store the Local Data into MongoDB Atlas(cloud)

### OUTCOMES

- 1. Load the Dataset into local enviroment

- 2. Some Basic Operation

- 3. Load the Dataset into MongoDB Atlas (cloud)

### 1. Load the Dataset into local enviroment

In [1]:
print("ok")

ok

In [4]:
# import necessary libraries
import pandas as pd

In [2]:
# show the Present working directory
%pwd

'e:\\Data Science\\Project\\MACHINE_LEARNING_PROJECTS\\shipment-price-predictor\\notebooks'

- Key NOTE:
    - Here show, I am insid the notebooks files

    - For access the Shipment-data.csv, 
        - First we go to the root directory
            - command: ../data/Shipment-data.csv
            - where, 
                - ../ means -> go the Root Directory

In [5]:
# load the dataset
data = pd.read_csv("../data/Shipment-data.csv")

data.head()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,Yes,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,No,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,No,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,No,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,Yes,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

### 2. Some Basic Operation

In [6]:
# Show first 5 rows
data.head()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,Yes,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,No,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,No,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,No,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,Yes,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

In [7]:
# show last 5 rows
data.tail()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
6495,fffe3800370037003300,Jeffrey Freudenthal,0.37,37.0,10.0,16551.0,Brass,28.28,38.46,Yes,Yes,No,Airways,No,Wealthy,Yes,03/28/18,03/25/18,"New Robert, VT 85335",872.43
6496,fffe310036003400,Larry Edwards,0.67,15.0,NaN,18981.0,NaN,67.18,27.72,No,No,No,Roadways,No,Working Class,No,08/29/15,08/27/15,"New Joshua, VA 35766",1347.02
6497,fffe3600300031003300,Denise Worth,0.68,19.0,8.0,587.0,Clay,6.92,10.38,Yes,No,No,NaN,Yes,Wealthy,No,04/10/19,04/09/19,"Lake Kelly, MA 80823",354.55
6498,fffe3600350035003900,Daniel Drew,0.02,33.0,9.0,1269377.0,Stone,2929.13,69.76,No,Yes,No,Roadways,No,Working Class,Yes,03/10/19,03/12/19,"Hintonberg, UT 35006",5037.50
6499,fffe3700310031003600,Vernon Carroll,0.18,30.0,13.0,34729.0,Brass,46.63,78.25,No,Yes,No,Airways,No,Working Class,No,12/03/16,12/05/16,"New Christopher, AK 87406",722.47

In [8]:
# shape of the data
data.shape

(6500, 20)

- Short Note:
    - Total number of rows = 25480
    - Total number of columns = 12

In [9]:
# show the dtype and memory usage
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer Id            6500 non-null   object
 1   Artist Name            6500 non-null   object
 2   Artist Reputation      5750 non-null   float64
 3   Height                 6125 non-null   float64
 4   Width                  5916 non-null   float64
 5   Weight                 5913 non-null   float64
 6   Material               5736 non-null   object
 7   Price Of Sculpture     6500 non-null   float64
 8   Base Shipping Price    6500 non-null   float64
 9   International          6500 non-null   object
 10  Express Shipment       6500 non-null   object
 11  Installation Included  6500 non-null   object
 12  Transport              5108 non-null   object
 13  Fragile                6500 non-null   object
 14  Customer Information   6500 non-null   object
 15  Remote Location        5729 non-null   object
 16  Scheduled Date         6500 non-null   object
 17  Delivery Date          6500 non-null   object
 18  Customer Location      6500 non-null   object
 19  Cost                   6500 non-null   float64
dtypes: float64(7), object(13)
memory usage: 1015.8+ KB

In [10]:
# type of dataset
type(data)

pandas.core.frame.DataFrame

### Convert Pandas DataFrame to Dictionary

- Because MongoDB store the data into json or dictionary format

- orient = "records": Give the well structure

In [11]:
data_dic = data.to_dict(orient = "records")

In [13]:
# length
len(data_dic)

6500

In [14]:
# Check type of data
type(data_dic)

list

### 3. Load the Dataset into MongoDB Atlas (cloud)

In [22]:
# import library
import pymongo

In [ ]:
# Database name
DB_NAME = "Shipment_Kz"
COLLECTION_NAME = "shipment_collection"
CONNECTION_URL = "Your_MONGO_BD_CONNECTION_URL"

- short note:

    - DB_NAME = Database name

    - COLLECTION_NAME = Table name of the Database

    - CONNECTION_URL = Connection string between MongoDB Atlas and python

### Storing Data to MongoDB Database

In [24]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [25]:
rec = collection.insert_many(data_dic)

### Fetching Data from MongoDB Database

In [27]:
# Fetching all records
records = collection.find()

In [28]:
# it give us an object of the data and it can be iterable
records

In [ ]:
# one one to display
# for i in records:
#     print(i)

### Convert records into DataFrame

In [29]:
# fetching all record from the MongoDB atlas and convert into dataframe
df = pd.DataFrame(list(collection.find()))

In [30]:
# show first 5 rows
df.head()

,_id,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,...,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,6a64cd4b89527e4ad7be00cc,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,...,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,6a64cd4b89527e4ad7be00cd,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,...,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,6a64cd4b89527e4ad7be00ce,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,...,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,6a64cd4b89527e4ad7be00cf,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,...,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,6a64cd4b89527e4ad7be00d0,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,...,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

In [31]:
# Drop the _id columns
if "_id" in df.columns:
    df.drop(columns="_id", inplace=True)

- Key Note:
    - Because, MongoDB Create a unique Id for a dataset.

In [32]:
df.head()

,Customer Id,Artist Name,Artist Reputation,Height,Width,Weight,Material,Price Of Sculpture,Base Shipping Price,International,Express Shipment,Installation Included,Transport,Fragile,Customer Information,Remote Location,Scheduled Date,Delivery Date,Customer Location,Cost
0,fffe3900350033003300,Billy Jenkins,0.26,17.0,6.0,4128.0,Brass,13.91,16.27,Yes,Yes,No,Airways,No,Working Class,No,06/07/15,06/03/15,"New Michelle, OH 50777",-283.29
1,fffe3800330031003900,Jean Bryant,0.28,3.0,3.0,61.0,Brass,6.83,15.00,No,No,No,Roadways,No,Working Class,No,03/06/17,03/05/17,"New Michaelport, WY 12072",-159.96
2,fffe3600370035003100,Laura Miller,0.07,8.0,5.0,237.0,Clay,4.96,21.18,No,No,No,Roadways,Yes,Working Class,Yes,03/09/15,03/08/15,"Bowmanshire, WA 19241",-154.29
3,fffe350031003300,Robert Chaires,0.12,9.0,NaN,NaN,Aluminium,5.81,16.31,No,No,No,NaN,No,Wealthy,Yes,05/24/15,05/20/15,"East Robyn, KY 86375",-161.16
4,fffe3900320038003400,Rosalyn Krol,0.15,17.0,6.0,324.0,Aluminium,3.18,11.94,Yes,Yes,Yes,Airways,No,Working Class,No,12/18/16,12/14/16,"Aprilside, PA 52793",-159.23

#### Convert DataFrame to CSV format

In [33]:
# convert DataFrame -> CSV
df.to_csv("shipment.csv", index = False)

### Deleted the DataBase

In [ ]:
# Deleted Database
# client.drop_database("KzRaihan")